### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by slee7268** [cshaley/predicted_bracket_generator#3]
I can't install this via pip install. there is a syntax error in setup.py 
I get an error tracing to line 11, the download_url. I think the "f" at the beginning is causing this. Thanks for making this!

**Comment by cshaley** [comment]
It works with python 3.6 and is not backward compatible to 2.7.

**Comment by slee7268** [comment]
Hi,

I'm getting an index error. Any help?

IndexError                                Traceback (most recent call
last)<ipython-input-147-966dbadcf548> in <module>      7
submissionPath='submission/logit2.csv',      8
slotsPath=path+'NCAA/NCAATourneySlots.csv',----> 9         year=2019
  10 )
~/anaconda3/lib/python3.7/site-packages/bracketeer/__init__.py in
build_bracket(outputPath, teamsPath, seedsPath, slotsPath,
submissionPath, year)    130         st = '{seed} {team}
{pred}'.format(    131             seed=seed_slot_map[key.value],-->
132             team=df[df['seed'] ==
seed_slot_map[key.value]][TEAM].values[0],    133
pred=pred    134         )
IndexError: index 0 is out of bounds for axis 0 with size 0


Thanks


Sam

**Comment by cshaley** [comment]
I think the official season in the Kaggle dataset is 2018, so try that for the year in place of 2019
